title: "Nahid Ahmed"
logo: /assets/img/Crop_circle.png
description: "EEE Graduate | Learner | Optimistic"

social_links:
  github: nahid1602
  linkedin: nahidahmed-eee
  email: nahidahmed.buet@gmail.com

theme: jekyll-theme-minimal
